services:
  
  sft:
    shm_size: '8gb'
    build:
        context:  .
        dockerfile: Dockerfile
    restart: always

    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - HF_HOME=/hf/
        - JUPYTER_TOKEN=token
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - '8889:8888'
    logging:
        options:
            max-size: "10m"
            max-file: "3"
    volumes:
          - ${HF_HOME}:/hf
          - ../models:/app/models
          - ../datasets:/app/datasets
          - ./notebooks:/app/notebooks
    deploy:
      resources:
        reservations:
          memory: 60GB
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


          
    
    
    
 