services:
  llm-dev-postgresql:
      image: pgvector/pgvector:pg16 #postgis/postgis:latest
      hostname: llmpg
      container_name: llmpg
      ports:
          - "5434:5432"
      environment:
          POSTGRES_DB: "llm"
          POSTGRES_USER: "llm"
          POSTGRES_PASSWORD: "llm"
      volumes:
          # - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
          - ./data/postgresql:/var/lib/postgresql/data
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgresql"]
          interval: 10s
          timeout: 5s
          retries: 5
      logging:
        options:
          max-size: "10m"
          max-file: "3"
